In [1]:
import numpy as np

### 1. Array creation
Create 1D and 2D arrays from lists. Also create arrays using arange, linspace, zeros, ones, and eye.

In [15]:
list1 = [1, 2, 3, 4]

list2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr1 = np.array(list1)

arr2 = np.array(list2)

print(arr1)
print("="*20)

print(arr2)
print("="*20)

arr_arange = np.arange(5)
print(arr_arange)

print("="*20)

arr_linspace = np.linspace(4,5)
print(arr_linspace)

print("="*20)

arr0 = np.zeros((5,5))
print(arr0)

print("="*20)

arr_1 = np.ones((5,5))
print(arr_1)

print("="*20)

arr_eye = np.eye(5)
print(arr_eye)

[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4]
[4.         4.02040816 4.04081633 4.06122449 4.08163265 4.10204082
 4.12244898 4.14285714 4.16326531 4.18367347 4.20408163 4.2244898
 4.24489796 4.26530612 4.28571429 4.30612245 4.32653061 4.34693878
 4.36734694 4.3877551  4.40816327 4.42857143 4.44897959 4.46938776
 4.48979592 4.51020408 4.53061224 4.55102041 4.57142857 4.59183673
 4.6122449  4.63265306 4.65306122 4.67346939 4.69387755 4.71428571
 4.73469388 4.75510204 4.7755102  4.79591837 4.81632653 4.83673469
 4.85714286 4.87755102 4.89795918 4.91836735 4.93877551 4.95918367
 4.97959184 5.        ]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 2. Array inspection
Check shape, size, ndim, dtype, and itemsize of a given array.

In [21]:
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.ndim)
print(arr2.itemsize)

(3, 3)
9
int32
2
4


## 3. Indexing & slicing
Access individual elements, rows, columns, and sub-arrays from a 2D array.

In [32]:
print(arr2[1][2])

print("="*20)

print(arr2[1])

print("="*20)

print(arr2[:, 0])

print("="*20)

subarr = arr2[2]

print(subarr)

6
[4 5 6]
[1 4 7]
[7 8 9]


## 4. Basic arithmetic
Perform element-wise addition, subtraction, multiplication, division, and power on two arrays.

In [16]:
arr3 = np.array([
    [5, 6, 7],
    [8, 9, 0],
    [1, 2, 3]
])

print(arr2 + arr3)

print("="*20)

print(arr2 - arr3)

print("="*20)

print(arr2.dot(arr3))

print("="*20)

print(arr3/arr2)

print("="*20)

print(arr3**2)

[[ 6  8 10]
 [12 14  6]
 [ 8 10 12]]
[[-4 -4 -4]
 [-4 -4  6]
 [ 6  6  6]]
[[ 24  30  16]
 [ 66  81  46]
 [108 132  76]]
[[5.         3.         2.33333333]
 [2.         1.8        0.        ]
 [0.14285714 0.25       0.33333333]]
[[25 36 49]
 [64 81  0]
 [ 1  4  9]]


## 5. Descriptive statistics
Compute mean, median, standard deviation, min, max, and percentiles on a 1D array.

In [17]:
print(np.mean(arr2))

print("="*20)

print(np.median(arr2))

print("="*20)

print(np.std(arr2))

print("="*20)

print(np.minimum(arr2, arr3))

print("="*20)

print(np.maximum(arr2, arr3))

print("="*20)

arr1 = np.array([88, 72, 95, 61, 79, 84, 90, 55, 68, 77, 92, 83])

print(np.percentile(arr1, 25))
print(np.percentile(arr1, 50))
print(np.percentile(arr1, 75))

5.0
5.0
2.581988897471611
[[1 2 3]
 [4 5 0]
 [1 2 3]]
[[5 6 7]
 [8 9 6]
 [7 8 9]]
71.0
81.0
88.5


## 6. Array sorting
Sort a 1D array in ascending and descending order. Also find the indices that would sort it using argsort.

In [19]:
arr = np.array([5, 2, 7, 4, 1, 6])

print(np.sort(arr))

print("="*20)

print(np.sort(arr)[::-1])

print("="*20)

idx = np.argsort(arr)
print("argsort: ", idx)
print("Sorted via argsort: ", arr[idx])

print("="*20)

top3_idx = np.argsort(arr)[-3:][::-1]
print(top3_idx)
print(arr[top3_idx])

print("="*20)

arr.sort()
print(arr)

[1 2 4 5 6 7]
[7 6 5 4 2 1]
argsort:  [4 1 3 0 5 2]
Sorted via argsort:  [1 2 4 5 6 7]
[2 5 0]
[7 6 5]
[1 2 4 5 6 7]


## 7. Type casting
Convert array dtypes from int to float, float to int, and int to string using astype.

In [ ]:
read = [23.7, 18.2, 30.5, 25.9, 14.1]
label   = ['23', '18', '30', '25', '14']

reading = np.array(read)
labels = np.array(label)

