In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [5]:
print(a + b)
print(a - b)
print(a * b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [8]:
a = a ** 2
np.dot(a, b)

78

In [11]:
a > 2

array([False,  True,  True])

In [12]:
np.where(a > 1, a, 0)

array([0, 4, 9])

In [14]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

In [16]:
np.dot(d, c)

array([[23, 34],
       [31, 46]])

In [17]:
np.cross(c, d)

array([-4, -4])

In [19]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.seed(42)

In [25]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.random.rand(2, 3)

array([[0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985]])

In [30]:
np.random.randn(3, 3)

array([[-0.46947439,  0.54256004, -0.46341769],
       [-0.46572975,  0.24196227, -1.91328024],
       [-1.72491783, -0.56228753, -1.01283112]])

In [31]:
np.random.randint(0, 10, (3, 3))

array([[2, 6, 3],
       [8, 2, 4],
       [2, 6, 4]])

In [32]:
c.shape

(2, 2)

In [34]:
c.ndim

2

In [35]:
c.dtype

dtype('int32')

In [36]:
c.size

4

In [37]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [38]:
A[1, 2]

6

In [42]:
A[0]

array([1, 2, 3])

In [43]:
A[:, 2]

array([3, 6, 9])

In [45]:
A[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [46]:
mask = A > 5
A[mask]

array([6, 7, 8, 9])

In [47]:
x = np.array([
    [1, 3],
    [2, 4]
])

In [51]:
np.sum(x)

10

In [52]:
np.sum(x, axis = 0)

array([3, 7])

In [54]:
np.sum(x, axis = 1)

array([4, 6])

In [55]:
np.mean(x)

2.5

In [56]:
np.max(x)

4

In [58]:
np.std(x)

1.118033988749895

In [60]:
np.var(x)

1.25

In [61]:
np.min(x)

1

In [62]:
np.sqrt(x)

array([[1.        , 1.73205081],
       [1.41421356, 2.        ]])

In [63]:
np.log(x)

array([[0.        , 1.09861229],
       [0.69314718, 1.38629436]])

In [64]:
np.exp(x)

array([[ 2.71828183, 20.08553692],
       [ 7.3890561 , 54.59815003]])

In [66]:
np.argmax(x, axis = 1)

array([1, 1], dtype=int64)

In [68]:
np.argmin(x, axis = 0)

array([0, 0], dtype=int64)

In [69]:
np.abs(x)

array([[1, 3],
       [2, 4]])

In [70]:
np.linalg.det(A)

6.66133814775094e-16

In [71]:
np.linalg.inv(A)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [72]:
np.linalg.norm(A)

16.881943016134134

In [73]:
np.linalg.norm(A, 2)

16.84810335261421

In [74]:
vals, vecs = np.linalg.eig(A)

In [76]:
print(vals, vecs)

[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16] [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [79]:
m = np.array([4, 5, 6])

n = np.linalg.solve(A, m)

In [80]:
print(x)

[[1 3]
 [2 4]]


In [81]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])