In [1]:
import numpy as np

# Basic

### 1. Array creation
Create 1D and 2D arrays from lists. Also create arrays using arange, linspace, zeros, ones, and eye.

In [15]:
list1 = [1, 2, 3, 4]

list2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr1 = np.array(list1)

arr2 = np.array(list2)

print(arr1)
print("="*20)

print(arr2)
print("="*20)

arr_arange = np.arange(5)
print(arr_arange)

print("="*20)

arr_linspace = np.linspace(4,5)
print(arr_linspace)

print("="*20)

arr0 = np.zeros((5,5))
print(arr0)

print("="*20)

arr_1 = np.ones((5,5))
print(arr_1)

print("="*20)

arr_eye = np.eye(5)
print(arr_eye)

[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4]
[4.         4.02040816 4.04081633 4.06122449 4.08163265 4.10204082
 4.12244898 4.14285714 4.16326531 4.18367347 4.20408163 4.2244898
 4.24489796 4.26530612 4.28571429 4.30612245 4.32653061 4.34693878
 4.36734694 4.3877551  4.40816327 4.42857143 4.44897959 4.46938776
 4.48979592 4.51020408 4.53061224 4.55102041 4.57142857 4.59183673
 4.6122449  4.63265306 4.65306122 4.67346939 4.69387755 4.71428571
 4.73469388 4.75510204 4.7755102  4.79591837 4.81632653 4.83673469
 4.85714286 4.87755102 4.89795918 4.91836735 4.93877551 4.95918367
 4.97959184 5.        ]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 2. Array inspection
Check shape, size, ndim, dtype, and itemsize of a given array.

In [21]:
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.ndim)
print(arr2.itemsize)

(3, 3)
9
int32
2
4


## 3. Indexing & slicing
Access individual elements, rows, columns, and sub-arrays from a 2D array.

In [32]:
print(arr2[1][2])

print("="*20)

print(arr2[1])

print("="*20)

print(arr2[:, 0])

print("="*20)

subarr = arr2[2]

print(subarr)

6
[4 5 6]
[1 4 7]
[7 8 9]


## 4. Basic arithmetic
Perform element-wise addition, subtraction, multiplication, division, and power on two arrays.

In [16]:
arr3 = np.array([
    [5, 6, 7],
    [8, 9, 0],
    [1, 2, 3]
])

print(arr2 + arr3)

print("="*20)

print(arr2 - arr3)

print("="*20)

print(arr2.dot(arr3))

print("="*20)

print(arr3/arr2)

print("="*20)

print(arr3**2)

[[ 6  8 10]
 [12 14  6]
 [ 8 10 12]]
[[-4 -4 -4]
 [-4 -4  6]
 [ 6  6  6]]
[[ 24  30  16]
 [ 66  81  46]
 [108 132  76]]
[[5.         3.         2.33333333]
 [2.         1.8        0.        ]
 [0.14285714 0.25       0.33333333]]
[[25 36 49]
 [64 81  0]
 [ 1  4  9]]


## 5. Descriptive statistics
Compute mean, median, standard deviation, min, max, and percentiles on a 1D array.

In [17]:
print(np.mean(arr2))

print("="*20)

print(np.median(arr2))

print("="*20)

print(np.std(arr2))

print("="*20)

print(np.minimum(arr2, arr3))

print("="*20)

print(np.maximum(arr2, arr3))

print("="*20)

arr1 = np.array([88, 72, 95, 61, 79, 84, 90, 55, 68, 77, 92, 83])

print(np.percentile(arr1, 25))
print(np.percentile(arr1, 50))
print(np.percentile(arr1, 75))

5.0
5.0
2.581988897471611
[[1 2 3]
 [4 5 0]
 [1 2 3]]
[[5 6 7]
 [8 9 6]
 [7 8 9]]
71.0
81.0
88.5


## 6. Array sorting
Sort a 1D array in ascending and descending order. Also find the indices that would sort it using argsort.

In [19]:
arr = np.array([5, 2, 7, 4, 1, 6])

print(np.sort(arr))

print("="*20)

print(np.sort(arr)[::-1])

print("="*20)

idx = np.argsort(arr)
print("argsort: ", idx)
print("Sorted via argsort: ", arr[idx])

print("="*20)

top3_idx = np.argsort(arr)[-3:][::-1]
print(top3_idx)
print(arr[top3_idx])

print("="*20)

arr.sort()
print(arr)

[1 2 4 5 6 7]
[7 6 5 4 2 1]
argsort:  [4 1 3 0 5 2]
Sorted via argsort:  [1 2 4 5 6 7]
[2 5 0]
[7 6 5]
[1 2 4 5 6 7]


## 7. Type casting
Convert array dtypes from int to float, float to int, and int to string using astype.

In [ ]:
read = [23.7, 18.2, 30.5, 25.9, 14.1]
label   = ['23', '18', '30', '25', '14']

reading = np.array(read)
labels = np.array(label)



# Intermediate

## 1. Reshaping & flattening
Reshape a 1D array into 2D and 3D. Flatten and ravel it back. Understand the difference between the two.

In [9]:
a = np.arange(12)

b = a.reshape(3, 4)
c = a.reshape(2, 2, 3)

d = a.flatten()
e = a.ravel()

print(a)
print("="*20)

print(b)
print("="*20)

print(c)
print("="*20)

print(d)
print("="*20)

print(e)
print("="*20)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## 2. Stacking & splitting
Stack two arrays using vstack, hstack, and concatenate. Split an array into equal parts using array_split.

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.vstack([a, b]))
print(np.hstack([a, b]))

print(np.concatenate([a, b], axis = 1))
print(np.concatenate([a, b], axis = 0))

x = np.arange(12)

parts = np.array_split(x, 3)
print(parts)

print(np.array_split(x, [3, 8]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]


## 3. Broadcasting
Add a 1D array to each row of a 2D array without loops. Normalize a matrix row-wise using broadcasting.

In [12]:
M = np.ones([3, 4])
v = np.array([10, 20, 30, 40])

print(M + v)

B = np.random.randint(1, 10, (4, 3))
row_sum = B.sum(axis = 1, keepdims = True)

normalized = B / row_sum

print(normalized)

[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]
[[0.28571429 0.38095238 0.33333333]
 [0.05882353 0.52941176 0.41176471]
 [0.69230769 0.23076923 0.07692308]
 [0.2        0.6        0.2       ]]


## 4. Boolean masking
Filter elements from an array using conditions. Apply compound conditions using & and | operators.

In [14]:
a = np.array([2, 5, 3, 1, 7, 0, 6])

mask = a > 4

print(a[mask])
print(a[a > 5])

print(a[(a > 2) & (a < 6)])
print(a[(a < 3) | (a > 5)])
print(a[~(a > 5)])

[5 7 6]
[7 6]
[5 3]
[2 1 7 0 6]
[2 5 3 1 0]


## 5. Fancy indexing
Select specific rows and columns using integer arrays as indices. Modify selected elements in-place.

In [16]:
a = np.array([10, 20, 30, 40, 50])

idx = [0, 2, 4]

print(a[idx])
print(a[[-1, 1, 3]])

M = np.arange(16).reshape(4, 4)

print(M[[0, 2]])
print(M[[0, 2], [1, 3]])
M[[1, 3]] = -1

print(M)

[10 30 50]
[50 20 40]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[ 1 11]
[[ 0  1  2  3]
 [-1 -1 -1 -1]
 [ 8  9 10 11]
 [-1 -1 -1 -1]]


## 6.  Aggregation along axes
Compute sum, mean, max along axis=0 and axis=1 of a 2D array. Use keepdims to preserve shape.

In [18]:
M = np.array([[1, 2, 3], [4, 5, 6]])

print(M.sum(axis = 0))
print(M.sum(axis = 1))
print(M.sum())

print(M.sum(axis = 1))
print(M.sum(axis = 1, keepdims = True))

print(M.mean(axis =0))
print(M.max(axis = 1, keepdims = True))

[5 7 9]
[ 6 15]
21
[ 6 15]
[[ 6]
 [15]]
[2.5 3.5 4.5]
[[3]
 [6]]


## 7. Random number generation
Generate random integers, floats, and normally distributed data. Set a seed for reproducibility.

In [22]:
import random

rng = np.random.default_rng(seed = 12)

print(rng.integers(0, 10, size = (3, 4)))

print(rng.random(size = (3, 3)))

print(rng.standard_normal(size = (3, 3)))

print(rng.normal(loc = 5.0, scale = 2.0, size = 100))

print(np.random.seed(42))
print(np.random.randint(0, 10, (3, 4)))
print(np.random.random((2, 5)))
print(np.random.randn(3, 3))

[[6 2 9 9]
 [0 1 1 1]
 [5 3 4 2]]
[[0.67044574 0.11507938 0.89630937]
 [0.85813049 0.00282703 0.54146616]
 [0.10685127 0.25795496 0.41689604]]
[[ 1.77538939  0.88684908  0.94934948]
 [-0.05785496  0.61286227  0.65789016]
 [-0.34440267 -0.49737204 -0.11477278]]
[3.78909598 3.81132116 4.43324925 3.54316455 6.53265557 1.80782733
 6.64712426 3.74886706 3.90812009 2.29830572 4.71151576 4.50467698
 5.38291166 3.93245141 5.18751236 8.63938368 5.81799939 3.85261993
 6.90621919 4.74239773 6.18774894 6.22549486 4.21786857 1.139425
 4.30469275 6.10291085 4.23977919 5.87793863 6.95908074 3.91177317
 7.46270351 8.24360892 7.15809189 7.33092568 7.1935929  9.50907812
 5.37172181 5.00416817 6.20621461 3.18360976 1.89364647 3.23598405
 5.7451307  5.94610668 1.92728256 1.23307258 4.36771551 4.62388697
 4.90159833 6.34272489 7.45766836 5.46179286 6.22536941 2.80959661
 2.64738397 5.47247667 6.32932621 6.45248691 6.18548398 6.56834742
 6.61965606 1.49562927 3.53166846 5.91031948 6.19334393 1.97581518
 7.3

## 8. np.where & np.select
Use np.where to apply conditional logic. Use np.select for multiple condition branches.

In [23]:
a = np.array([-3, 5, -1, 8, 0])

print(np.where(a > 0, a, 0))

print(np.where(a > 0, 'pos', 'non-pos'))

print(np.where(a > 0))

conditions = [
    a < 0,
    a == 0,
    a < 10
]

choices = ['negative', 'zero', 'positive']

print(np.select(conditions, choices, default = 'large'))

[0 5 0 8 0]
['non-pos' 'pos' 'non-pos' 'pos' 'non-pos']
(array([1, 3], dtype=int64),)
['negative' 'positive' 'negative' 'positive' 'zero']


# Advanced

## 1. Matrix operations
Perform matrix multiplication using @, compute transpose, inverse, and determinant of a matrix.

In [5]:
X = np.array(
    [[1, 2, 3],
    [4, 5, 8],
    [6, 7, 9]]
)

Y = np.array(
    [[3, 4, 5],
    [6, 9, 8],
    [1, 7, 2]]
)

print(X.T)

print("="*20)

print(Y.T)

print("="*20)

print(X @ Y)

print("="*20)

from numpy.linalg import inv, det

print(inv(X))

print("="*20)

print(inv(Y))

print("="*20)

print(det(X))

print("="*20)

print(det(Y))

[[1 4 6]
 [2 5 7]
 [3 8 9]]
[[3 6 1]
 [4 9 7]
 [5 8 2]]
[[ 18  43  27]
 [ 50 117  76]
 [ 69 150 104]]
[[-1.57142857  0.42857143  0.14285714]
 [ 1.71428571 -1.28571429  0.57142857]
 [-0.28571429  0.71428571 -0.42857143]]
[[-1.08571429  0.77142857 -0.37142857]
 [-0.11428571  0.02857143  0.17142857]
 [ 0.94285714 -0.48571429  0.08571429]]
6.9999999999999964
34.99999999999999


## 2. Solving linear equations
Solve a system of linear equations Ax = b using np.linalg.solve. Verify the solution.